apiVersion: apps/v1

kind: Deployment

metadata:

  name: calculator-app

spec:

  replicas: 3

  selector:

    matchLabels:

      app: calculator

  template:

    metadata:

      labels:

        app: calculator

    spec:

      containers:

      - name: calculator

        image: admin/calculator-app:v1

        ports:

        - containerPort: 5000